#define DIO_PIN_0 OUTPUT_LOW
#define DIO_PIN_1 OUTPUT_HIGH
#define DIO_PIN_2 INPUT_PULL_UP
#define DIO_PIN_3 INPUT_PULL_UP
#define DIO_PIN_4 INPUT_PULL_UP
#define DIO_PIN_5 INPUT_HIGH_IMP
#define DIO_PIN_6 INPUT_HIGH_IMP
#define DIO_PIN_7 OUTPUT_HIGH
